### PR TITLE
Update Action.updateRenderer to be an instance method

### PR DESCRIPTION
**Pull request by smaramba**
As pointed out by @danappelxx on this Reddit post:
https://www.reddit.com/r/swift/comments/5d98u4/katana_is_a_modern_swift_framework_for_writing/

for legacy reasons, to compute the next state given an action, we are using a static method `Action.updatedState(currentState:State, action: Action)`.

With this PR we are introducing the instance method `updatedState(currentState:)` instead.
__before__: `DecrementCounter.updatedState(currentState: State, action: DecrementCounter)`
__after__:  `DecrementCounter().updatedState(currentState: State)`

thanks again to Danappelxx, for pointing this out.

### CODE REVIEW

**Comment by lucaquerella** [comment]
@Danappelxx

**Comment by lucaquerella** [comment]
SGTM anyway

**Comment by Danappelxx** [comment]
Nice to see this so quickly! Definitely gives me faith in the project :) Changes look good to me.

**Comment by bolismauro** [comment]
@Danappelxx Thanks again.
STGM, I've also updated the documentation. We will release the `0.3.0` today I guess

**Pull request merged**
